import { useEffect, useMemo, useState } from 'react'
import { ArrowDownUp, ArrowLeft, ArrowRight, BadgeCheck, Bell, Check, ChevronDown, Clock3, CreditCard, Flame, Leaf, LogIn, Minus, Plus, Search, ShoppingBag, ShoppingCart, SlidersHorizontal, Sparkles, Star, Trash2, UtensilsCrossed, X } from 'lucide-react'
import { biryaniImage, buttermilkImage, gulabJamunImage, initialItems, initialOrders, limeCoolerImage, pickupSlots, type FoodItem, type Order, type OrderStatus, type User } from './data'
import { demoAuthAdapter } from './services/auth'
import './App.css'
import './campusbite.css'

type Page = 'menu' | 'cart' | 'orders' | 'admin' | 'offers' | 'about'
type CartLine = { itemId: string; quantity: number; extras: string[] }
const money = (amount: number) => `₹${amount.toFixed(0)}`
const imageFallback = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=85'

function useStoredState<T>(key: string, initial: T) {
  const [state, setState] = useState<T>(() => { try { const saved = localStorage.getItem(key); return saved ? JSON.parse(saved) as T : initial } catch { return initial } })
  useEffect(() => { localStorage.setItem(key, JSON.stringify(state)) }, [key, state])
  return [state, setState] as const
}

export default function CampusBite() {
  const [items, setItems] = useStoredState<FoodItem[]>('campusbite-items', initialItems)
  const [orders, setOrders] = useStoredState<Order[]>('campusbite-orders', initialOrders)
  const [slots, setSlots] = useStoredState<typeof pickupSlots>('campusbite-slots', pickupSlots)
  const [cart, setCart] = useStoredState<CartLine[]>('campusbite-cart', [])
  const [user, setUser] = useStoredState<User | null>('campusbite-user', null)
  const [page, setPage] = useState<Page>('menu')
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const [sort, setSort] = useState('Popular')
  const [vegOnly, setVegOnly] = useState(false)
  const [availableOnly, setAvailableOnly] = useState(false)
  const [popularOnly, setPopularOnly] = useState(false)
  const [maxPrice, setMaxPrice] = useState(250)
  const [selectedItem, setSelectedItem] = useState<FoodItem | null>(null)
  const [authOpen, setAuthOpen] = useState(false)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [mobileNav, setMobileNav] = useState(false)

  useEffect(() => {
    setItems((current) => {
      const existingIds = new Set(current.map((item) => item.id))
      const merged = [...current, ...initialItems.filter((item) => !existingIds.has(item.id))]
      return merged.map((item) => {
        const image = item.id === 'biryani' ? biryaniImage : item.id === 'lemonade' ? limeCoolerImage : item.id === 'buttermilk' ? buttermilkImage : item.id === 'gulab-jamun' ? gulabJamunImage : item.image
        return image === item.image ? item : { ...item, image }
      })
    })
  }, [setItems])

  const cartCount = cart.reduce((sum, line) => sum + line.quantity, 0)
  const filteredItems = useMemo(() => items.filter((item) => {
    const matchesQuery = `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase())
    return matchesQuery && (category === 'All' || item.category === category) && item.price <= maxPrice && (!vegOnly || item.vegetarian) && (!availableOnly || item.available) && (!popularOnly || item.popular)
  }).sort((a, b) => sort === 'Price: Low to high' ? a.price - b.price : sort === 'Price: High to low' ? b.price - a.price : sort === 'Top rated' ? b.rating - a.rating : b.popularScore - a.popularScore), [items, query, category, maxPrice, vegOnly, availableOnly, popularOnly, sort])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const addToCart = (item: FoodItem, quantity = 1, extras: string[] = []) => { if (!item.available) return; setCart((current) => [...current, { itemId: item.id, quantity, extras }]); setSelectedItem(null); notify(`${item.name} added to your bag`) }
  const updateQuantity = (index: number, delta: number) => setCart((current) => current.map((line, i) => i === index ? { ...line, quantity: line.quantity + delta } : line).filter((line) => line.quantity > 0))
  const getItem = (id: string) => items.find((item) => item.id === id)
  const subtotal = cart.reduce((sum, line) => { const item = getItem(line.itemId); return sum + (item ? (item.price + line.extras.reduce((s, extra) => s + (extra.includes('cheese') ? 10 : 5), 0)) * line.quantity : 0) }, 0)
  const discount = subtotal >= 200 ? 20 : 0
  const total = subtotal - discount
  const placeOrder = (slot: string, payment: string) => {
    const order: Order = { id: `CB-${Date.now().toString().slice(-5)}`, student: user?.name ?? 'Campus guest', studentId: user?.collegeId ?? 'Guest', lines: cart, total, slot, payment, status: 'Received', createdAt: new Date().toISOString(), feedback: null }
    setOrders((current) => [order, ...current]); setSlots((current) => current.map((pickup) => pickup.time === slot ? { ...pickup, remaining: Math.max(0, pickup.remaining - 1) } : pickup)); setCart([]); setCheckoutOpen(false); setPage('orders'); notify('Order placed. The kitchen has been notified.')
  }
  const cancelOrder = (id: string) => {
    const order = orders.find((entry) => entry.id === id)
    if (!order || order.status !== 'Received') return
    setOrders((current) => current.map((entry) => entry.id === id ? { ...entry, status: 'Cancelled' } : entry))
    setSlots((current) => current.map((pickup) => pickup.time === order.slot ? { ...pickup, remaining: Math.min(pickup.capacity, pickup.remaining + 1) } : pickup))
  }
  const signIn = (role: 'student' | 'admin', name: string, collegeId: string) => {
    void demoAuthAdapter.authenticate({ role, name, identifier: collegeId, password: '' }).then((session) => {
      setUser(session); setAuthOpen(false); setPage(role === 'admin' ? 'admin' : 'menu'); notify(`Welcome ${session.name}`)
    })
  }

  return <div className="app-shell">
    <header className="topbar">
      <button className="brand" onClick={() => setPage('menu')} aria-label="CampusBite home"><span className="brand-mark"><UtensilsCrossed size={20} /></span><span>campus<span className="brand-accent">bite</span><small>THE CAMPUS CANTEEN</small></span></button>
      <button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle navigation">{mobileNav ? <X /> : <SlidersHorizontal />}</button>
      <nav className={mobileNav ? 'nav-links nav-open' : 'nav-links'} aria-label="Main navigation"><button className={page === 'menu' ? 'nav-link active' : 'nav-link'} onClick={() => { setPage('menu'); setMobileNav(false) }}>Menu</button><button className={page === 'orders' ? 'nav-link active' : 'nav-link'} onClick={() => { setPage('orders'); setMobileNav(false) }}>My orders</button><button className={page === 'offers' ? 'nav-link active' : 'nav-link'} onClick={() => { setPage('offers'); setMobileNav(false) }}>Offers <span className="offer-dot" /></button><button className={page === 'about' ? 'nav-link active' : 'nav-link'} onClick={() => { setPage('about'); setMobileNav(false) }}>About</button>{user?.role === 'admin' && <button className={page === 'admin' ? 'nav-link active' : 'nav-link'} onClick={() => { setPage('admin'); setMobileNav(false) }}>Staff workspace</button>}</nav>
      <div className="top-actions"><button className="icon-button notification-button" title="Notifications" onClick={() => notify('You are all caught up')}><Bell size={19} /><i /></button><button className="profile-button" onClick={() => user ? (user.role === 'admin' ? setPage('admin') : setAuthOpen(true)) : setAuthOpen(true)}><span className="avatar">{user ? user.name.charAt(0) : 'S'}</span><span className="profile-label">{user?.name.split(' ')[0] ?? 'Sign in'}</span><ChevronDown size={15} /></button><button className="cart-button" title="Open cart" onClick={() => setPage('cart')}><ShoppingCart size={19} /><span>Bag</span><b>{cartCount}</b></button></div>
    </header>
    <main>
      {page === 'menu' && <>
        <section className="welcome-strip"><span><span className="live-dot" /> OPEN NOW <i /> Mon–Sat, 8:00 AM – 5:00 PM</span><button onClick={() => setPage('orders')}>Track your order <ArrowRight size={14} /></button></section>
        <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14} /> A BETTER LUNCH BREAK</div><h1>Your food.<br /><em>Your time.</em><br />Your campus.</h1><p>Order from your college canteen and skip the waiting line. Good food, right on schedule.</p><div className="hero-buttons"><button className="button button-dark" onClick={() => document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' })}>Explore the menu <ArrowRight size={17} /></button><button className="text-button" onClick={() => setPage('orders')}><span className="play-icon"><Clock3 size={15} /></span> Follow an order</button></div><div className="hero-social"><div className="mini-avatars"><span>A</span><span>M</span><span>R</span><span>+</span></div><span><b>1,200+</b> happy campus appetites</span><span className="hero-rating"><Star size={13} fill="currentColor" /> 4.8 <small>canteen rating</small></span></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1300&q=90" alt="Freshly prepared pizza served at the campus canteen" /><div className="hero-image-tag"><span className="tag-icon"><Flame size={16} /></span><span><b>Made fresh,</b><small>served on your time</small></span><span className="tag-arrow"><ArrowRight size={15} /></span></div><div className="hero-sticker">GOOD<br />MOOD<br /><i>FOOD</i></div><div className="hero-image-caption"><span>01 / 04</span><span>THE LUNCH CLUB <ArrowRight size={12} /></span></div></div></section>
        <section className="quick-stats"><div><span className="stat-icon mint"><Clock3 size={17} /></span><span><b>Skip the queue</b><small>Pick up when you're ready</small></span></div><div><span className="stat-icon peach"><Leaf size={17} /></span><span><b>Made to order</b><small>Fresh from our kitchen</small></span></div><div><span className="stat-icon lemon"><BadgeCheck size={17} /></span><span><b>Student prices</b><small>Good food, fair prices</small></span></div><div className="stat-pickup"><span>Next pickup window</span><b>12:15 <small>PM</small></b><span className="pickup-open">6 spots left</span></div></section>
        <section className="menu-section" id="menu"><div className="section-heading"><div><div className="eyebrow muted-eyebrow">THE CANTEEN, REIMAGINED</div><h2>What's cooking<span>?</span></h2></div><button className="view-orders" onClick={() => setPage('orders')}>Your orders <ArrowRight size={15} /></button></div><div className="menu-tools"><div className="search-box"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search food, cravings, anything..." /><kbd>⌘ K</kbd></div><label className="sort-control"><ArrowDownUp size={15} /><select value={sort} onChange={(event) => setSort(event.target.value)}><option>Popular</option><option>Price: Low to high</option><option>Price: High to low</option><option>Top rated</option></select></label></div><div className="filter-row"><div className="category-tabs">{['All', 'Snacks', 'Meals', 'Beverages', 'Desserts'].map((name) => <button key={name} className={category === name ? 'category-tab selected' : 'category-tab'} onClick={() => setCategory(name)}>{name}</button>)}</div><div className="filter-options"><label className="price-filter"><span>Up to {money(maxPrice)}</span><input type="range" min="30" max="250" step="10" value={maxPrice} onChange={(event) => setMaxPrice(Number(event.target.value))} aria-label="Maximum price" /></label><button className={vegOnly ? 'filter-chip filter-active' : 'filter-chip'} onClick={() => setVegOnly(!vegOnly)}><Leaf size={14} /> Veg</button><button className={popularOnly ? 'filter-chip filter-active' : 'filter-chip'} onClick={() => setPopularOnly(!popularOnly)}><Flame size={14} /> Popular</button><button className={availableOnly ? 'filter-chip filter-active' : 'filter-chip'} onClick={() => setAvailableOnly(!availableOnly)}><Check size={14} /> Available</button></div></div><div className="results-note">{filteredItems.length} delicious things <span>·</span> made fresh today</div><div className="food-grid">{filteredItems.map((item, index) => <FoodCard key={item.id} item={item} index={index} onOpen={() => setSelectedItem(item)} onAdd={() => addToCart(item)} />)}</div>{filteredItems.length === 0 && <div className="empty-state"><span>🥣</span><h3>Nothing on the menu for that search</h3><p>Try another craving or clear a filter.</p><button className="button button-outline" onClick={() => { setQuery(''); setCategory('All'); setMaxPrice(250); setVegOnly(false); setPopularOnly(false); setAvailableOnly(false) }}>Clear filters</button></div>}</section>
        <section className="bottom-banner"><div><span className="eyebrow">YOUR 2 PM PICK-ME-UP</span><h2>Good afternoons<br />start with <em>good food.</em></h2><button className="button button-light" onClick={() => { setCategory('Beverages'); document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' }) }}>Find your fix <ArrowRight size={16} /></button></div><div className="banner-image"><img src="https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=850&q=85" alt="Iced coffee and a pastry" /></div><span className="banner-note">A LITTLE BREAK<br />GOES A LONG WAY</span></section>
      </>}
      {page === 'cart' && <CartPage cart={cart} items={items} total={total} subtotal={subtotal} discount={discount} onQty={updateQuantity} onRemove={(index) => setCart((current) => current.filter((_, i) => i !== index))} onBrowse={() => setPage('menu')} onCheckout={() => cart.length && setCheckoutOpen(true)} />}
      {page === 'orders' && <OrdersPage orders={orders.filter((order) => !user || user.role === 'admin' || order.studentId === user.collegeId)} items={items} onCancel={cancelOrder} onFeedback={(id, rating) => setOrders((current) => current.map((order) => order.id === id ? { ...order, feedback: rating } : order))} onBrowse={() => setPage('menu')} />}
      {page === 'admin' && <AdminPage items={items} orders={orders} slots={slots} setSlots={setSlots} setItems={setItems} setOrders={setOrders} notify={notify} />}
      {page === 'offers' && <OffersPage onMenu={() => { setPage('menu'); setMaxPrice(250) }} />}
      {page === 'about' && <AboutPage onMenu={() => setPage('menu')} />}
    </main>
    <footer className="footer"><span className="footer-brand">campus<span>bite</span></span><span>Made for the campus rush. <i>With love & a little extra chutney.</i></span><span>© 2026 CampusBite <span className="footer-dot">●</span> Fresh from the canteen</span></footer>
    {selectedItem && <ItemModal item={selectedItem} onClose={() => setSelectedItem(null)} onAdd={addToCart} />}{authOpen && <AuthModal onClose={() => setAuthOpen(false)} onSignIn={signIn} />}{checkoutOpen && <CheckoutModal slots={slots} total={total} onClose={() => setCheckoutOpen(false)} onConfirm={placeOrder} onSignIn={() => { setCheckoutOpen(false); setAuthOpen(true) }} user={user} />}{toast && <div className="toast"><span><Check size={16} /></span>{toast}</div>}
  </div>
}

function FoodCard({ item, index, onOpen, onAdd }: { item: FoodItem; index: number; onOpen: () => void; onAdd: () => void }) {
  return <article className={`food-card reveal reveal-${Math.min(index % 4, 3)}`}><button className="food-image" onClick={onOpen} aria-label={`View ${item.name} details`}><img src={item.image} alt={item.name} onError={(event) => { event.currentTarget.src = imageFallback }} /><span className={item.vegetarian ? 'diet-badge veg-badge' : 'diet-badge nonveg-badge'}><i />{item.vegetarian ? 'VEG' : 'NON-VEG'}</span>{item.popular && <span className="popular-badge"><Flame size={11} /> CROWD FAV</span>}{!item.available && <span className="sold-out">SOLD OUT</span>}<span className="card-arrow"><ArrowRight size={15} /></span></button><div className="food-info"><div className="food-title-row"><button onClick={onOpen} className="food-name">{item.name}</button><span className="food-rating"><Star size={12} fill="currentColor" />{item.rating.toFixed(1)}</span></div><p>{item.description}</p><div className="food-card-footer"><span className="food-price">{money(item.price)}<small> / serving</small></span><button className={item.available ? 'add-button' : 'add-button disabled'} onClick={onAdd} disabled={!item.available} aria-label={`Add ${item.name} to cart`}><Plus size={16} /><span>Add</span></button></div></div></article>
}

function CartPage({ cart, items, subtotal, discount, total, onQty, onRemove, onBrowse, onCheckout }: { cart: CartLine[]; items: FoodItem[]; subtotal: number; discount: number; total: number; onQty: (i: number, d: number) => void; onRemove: (i: number) => void; onBrowse: () => void; onCheckout: () => void }) {
  return <section className="inner-page"><div className="page-kicker"><button className="back-link" onClick={onBrowse}><ArrowLeft size={15} /> Back to menu</button><span>YOUR LITTLE FEAST</span></div><div className="inner-heading"><div><div className="eyebrow muted-eyebrow">ONE MORE THING</div><h1>Your bag<span>.</span></h1></div><span className="item-count">{cart.reduce((sum, line) => sum + line.quantity, 0)} items</span></div>{cart.length === 0 ? <div className="empty-state cart-empty"><span>🛍️</span><h3>Your bag's taking a break</h3><p>Find something delicious on the menu.</p><button className="button button-dark" onClick={onBrowse}>Browse the menu <ArrowRight size={16} /></button></div> : <div className="cart-layout"><div className="cart-lines">{cart.map((line, index) => { const item = items.find((food) => food.id === line.itemId); if (!item) return null; return <article className="cart-line" key={`${line.itemId}-${index}`}><img src={item.image} alt={item.name} onError={(event) => { event.currentTarget.src = imageFallback }} /><div className="cart-line-info"><span className="line-category">{item.category.toUpperCase()}</span><h3>{item.name}</h3><p>{line.extras.length ? line.extras.join(', ') : 'As it comes, fresh from the kitchen'}</p><div className="quantity-control"><button onClick={() => onQty(index, -1)} aria-label="Decrease quantity"><Minus size={14} /></button><span>{line.quantity}</span><button onClick={() => onQty(index, 1)} aria-label="Increase quantity"><Plus size={14} /></button></div></div><div className="cart-line-end"><b>{money(item.price * line.quantity)}</b><button className="remove-line" onClick={() => onRemove(index)} aria-label={`Remove ${item.name}`}><Trash2 size={15} /></button></div></article> })}<button className="continue-link" onClick={onBrowse}><Plus size={15} /> Add something else</button></div><aside className="order-summary"><div className="summary-top"><span>THE DAMAGE</span><ShoppingBag size={17} /></div><h3>Order summary</h3><div className="summary-row"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="summary-row discount-row"><span>CampusBite treat</span><b>− {money(discount)}</b></div><div className="summary-row pickup-row"><span>Pickup</span><b>Free</b></div><div className="summary-total"><span>Total</span><b>{money(total)}</b></div><button className="button button-dark checkout-button" onClick={onCheckout}>Pick a pickup time <ArrowRight size={17} /></button><p className="secure-note"><BadgeCheck size={14} /> No payment until you pick up</p></aside></div>}</section>
}

function OrdersPage({ orders, items, onCancel, onFeedback, onBrowse }: { orders: Order[]; items: FoodItem[]; onCancel: (id: string) => void; onFeedback: (id: string, rating: number) => void; onBrowse: () => void }) {
  const statuses: OrderStatus[] = ['Received', 'Accepted', 'Preparing', 'Ready', 'Completed']
  return <section className="inner-page"><div className="page-kicker"><button className="back-link" onClick={onBrowse}><ArrowLeft size={15} /> Back to menu</button><span>YOUR CANTEEN TIMELINE</span></div><div className="inner-heading"><div><div className="eyebrow muted-eyebrow">ALL YOUR CRAVINGS, ACCOUNTED FOR</div><h1>Your orders<span>.</span></h1></div><span className="item-count">{orders.length} total</span></div>{orders.length === 0 ? <div className="empty-state cart-empty"><span>🍱</span><h3>Your next favourite is waiting</h3><p>Your orders will show up here once you've had a bite.</p><button className="button button-dark" onClick={onBrowse}>Explore the menu <ArrowRight size={16} /></button></div> : <div className="orders-list">{orders.map((order) => <article className="order-card" key={order.id}><div className="order-card-head"><div><span className="line-category">ORDER {order.id}</span><h3>{order.lines.map((line) => items.find((item) => item.id === line.itemId)?.name).filter(Boolean).join(' + ')}</h3><span className="order-date">{new Date(order.createdAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</span></div><span className={`status-pill status-${order.status.toLowerCase()}`}><i />{order.status}</span></div><div className="order-details-row"><span><Clock3 size={15} /> Pickup {order.slot}</span><span>{order.lines.reduce((sum, line) => sum + line.quantity, 0)} items</span><b>{money(order.total)}</b></div>{order.status !== 'Cancelled' && order.status !== 'Rejected' && <div className="order-progress">{statuses.map((status, index) => <div key={status} className={`progress-step ${statuses.indexOf(order.status) >= index ? 'progress-done' : ''}`}><span>{index < statuses.indexOf(order.status) ? <Check size={12} /> : index + 1}</span><small>{status}</small></div>)}</div>}<div className="order-card-actions">{order.status === 'Received' && <button className="text-button cancel-button" onClick={() => onCancel(order.id)}>Cancel order</button>}{order.status === 'Ready' && <span className="ready-note"><Bell size={14} /> It's ready. See you at the counter!</span>}{order.status === 'Completed' && (order.feedback ? <span className="ready-note"><Star size={14} fill="currentColor" /> Thanks for your {order.feedback}-star rating</span> : <div className="feedback-row"><span>How was it?</span>{[1, 2, 3, 4, 5].map((rating) => <button key={rating} aria-label={`${rating} stars`} onClick={() => onFeedback(order.id, rating)}><Star size={16} /></button>)}</div>)}</div></article>)}</div>}</section>
}

function AdminPage({ items, orders, slots, setSlots, setItems, setOrders, notify }: { items: FoodItem[]; orders: Order[]; slots: typeof pickupSlots; setSlots: (slots: typeof pickupSlots | ((current: typeof pickupSlots) => typeof pickupSlots)) => void; setItems: (items: FoodItem[] | ((current: FoodItem[]) => FoodItem[])) => void; setOrders: (orders: Order[] | ((current: Order[]) => Order[])) => void; notify: (message: string) => void }) {
  const [tab, setTab] = useState<'Overview' | 'Orders' | 'Menu' | 'Pickup slots' | 'Feedback'>('Overview')
  const activeOrders = orders.filter((order) => !['Completed', 'Cancelled', 'Rejected'].includes(order.status))
  const sales = orders.filter((order) => order.status === 'Completed' && new Date(order.createdAt).toDateString() === new Date().toDateString()).reduce((sum, order) => sum + order.total, 0)
  const popular = [...items].sort((a, b) => b.popularScore - a.popularScore).slice(0, 3)
  const moveStatus = (id: string, status: OrderStatus) => {
    const order = orders.find((entry) => entry.id === id)
    setOrders((current) => current.map((entry) => entry.id === id ? { ...entry, status } : entry))
    if (status === 'Rejected' && order?.status === 'Received') setSlots((current) => current.map((pickup) => pickup.time === order.slot ? { ...pickup, remaining: Math.min(pickup.capacity, pickup.remaining + 1) } : pickup))
  }
  const addItem = () => { const id = `item-${Date.now()}`; setItems((current) => [{ id, name: 'New canteen special', description: 'A fresh addition to the menu', category: 'Snacks', price: 60, rating: 4.5, vegetarian: true, available: true, popular: false, popularScore: 0, image: imageFallback, ingredients: ['Ask the kitchen'], extras: [] }, ...current]); setTab('Menu'); notify('New menu item added') }
  return <section className="admin-page"><div className="admin-topline"><div><div className="eyebrow muted-eyebrow">CAMPUSBITE / CANTEEN OPS</div><h1>Good morning, manager<span>.</span></h1><p>Here’s what’s happening in your canteen today.</p></div><div className="admin-date"><span className="live-dot" /> SERVICE LIVE <b>{new Date().toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })}</b></div></div><div className="admin-tabs">{(['Overview', 'Orders', 'Menu', 'Pickup slots', 'Feedback'] as const).map((name) => <button key={name} className={tab === name ? 'admin-tab active' : 'admin-tab'} onClick={() => setTab(name as typeof tab)}>{name}{name === 'Orders' && activeOrders.length > 0 && <b>{activeOrders.length}</b>}</button>)}</div>
    {tab === 'Overview' && <><div className="admin-metrics"><Metric label="TODAY'S SALES" value={money(sales)} note="Completed orders" icon={<CreditCard size={18} />} color="mint" /><Metric label="IN THE KITCHEN" value={String(activeOrders.length).padStart(2, '0')} note="Orders in progress" icon={<ShoppingBag size={18} />} color="peach" /><Metric label="MENU ITEMS" value={String(items.length).padStart(2, '0')} note={`${items.filter((item) => item.available).length} currently available`} icon={<UtensilsCrossed size={18} />} color="lemon" /><Metric label="PICKUP SLOTS" value={`${slots.reduce((sum, pickup) => sum + pickup.remaining, 0)} / ${slots.reduce((sum, pickup) => sum + pickup.capacity, 0)}`} note="Spots available today" icon={<Clock3 size={18} />} color="blue" /></div><div className="admin-overview-grid"><div className="admin-panel"><div className="panel-heading"><div><span className="line-category">NEEDS YOUR ATTENTION</span><h3>Order queue</h3></div><button className="panel-link" onClick={() => setTab('Orders')}>All orders <ArrowRight size={14} /></button></div>{activeOrders.length === 0 ? <p className="panel-empty">It's quiet right now. Incoming orders will appear here.</p> : activeOrders.slice(0, 4).map((order) => <AdminOrderRow key={order.id} order={order} items={items} compact onStatus={moveStatus} />)}</div><div className="admin-panel popular-panel"><div className="panel-heading"><div><span className="line-category">THE STUDENTS HAVE SPOKEN</span><h3>Popular this week</h3></div><Flame size={18} /></div>{popular.map((item, index) => <div className="popular-item" key={item.id}><span className="popular-rank">0{index + 1}</span><img src={item.image} alt="" /><span><b>{item.name}</b><small>{item.popularScore} orders this week</small></span><span className="popular-spark">↗</span></div>)}</div></div></>}
    {tab === 'Orders' && <div className="admin-panel full-panel"><div className="panel-heading"><div><span className="line-category">LIVE SERVICE</span><h3>Incoming orders <span className="order-count-tag">{activeOrders.length} active</span></h3></div><span className="live-indicator"><i /> Updated just now</span></div>{orders.length === 0 ? <p className="panel-empty">No orders yet. They’ll arrive here as students check out.</p> : [...orders].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map((order) => <AdminOrderRow key={order.id} order={order} items={items} onStatus={moveStatus} />)}</div>}
    {tab === 'Menu' && <div className="admin-panel full-panel"><div className="panel-heading"><div><span className="line-category">YOUR COUNTER, YOUR MENU</span><h3>Menu management</h3></div><button className="button button-dark small-button" onClick={addItem}><Plus size={15} /> Add item</button></div><div className="menu-admin-list">{items.map((item) => <div className="menu-admin-row" key={item.id}><img src={item.image} alt="" /><div className="menu-admin-name"><b>{item.name}</b><small>{item.category} · {item.vegetarian ? 'Vegetarian' : 'Non-veg'}</small></div><label className="admin-price">₹<input aria-label={`${item.name} price`} type="number" min="1" value={item.price} onChange={(event) => setItems((current) => current.map((food) => food.id === item.id ? { ...food, price: Number(event.target.value) } : food))} /></label><label className="availability-toggle"><input type="checkbox" checked={item.available} onChange={() => setItems((current) => current.map((food) => food.id === item.id ? { ...food, available: !food.available } : food))} /><span>{item.available ? 'Available' : 'Unavailable'}</span></label><button className="remove-menu-item" title="Delete item" onClick={() => { setItems((current) => current.filter((food) => food.id !== item.id)); notify(`${item.name} removed`) }}><Trash2 size={15} /></button></div>)}</div></div>}
    {tab === 'Pickup slots' && <div className="admin-panel full-panel"><div className="panel-heading"><div><span className="line-category">KEEP THE QUEUE MOVING</span><h3>Pickup slot capacity</h3></div><span className="live-indicator"><i /> Today’s service</span></div>{slots.map((pickup, index) => <div className="slot-admin-row" key={pickup.time}><span><b>{pickup.time}</b><small>{pickup.remaining === 0 ? 'Fully booked' : `${pickup.remaining} spaces still available`}</small></span><label>Capacity<input type="number" min="0" max="50" value={pickup.capacity} onChange={(event) => setSlots((current) => current.map((value, slotIndex) => { if (slotIndex !== index) return value; const capacity = Number(event.target.value); return { ...value, capacity, remaining: Math.max(0, Math.min(capacity, value.remaining + capacity - value.capacity)) } }))} /></label><span className={pickup.remaining === 0 ? 'slot-capacity-full' : 'slot-capacity-open'}>{pickup.remaining} / {pickup.capacity} available</span></div>)}</div>}
    {tab === 'Feedback' && <div className="admin-panel full-panel"><div className="panel-heading"><div><span className="line-category">STRAIGHT FROM THE TABLE</span><h3>Student feedback</h3></div><span className="average-rating"><Star size={15} fill="currentColor" /> 4.8 average</span></div>{orders.filter((order) => order.feedback).length === 0 ? <p className="panel-empty">Feedback from completed orders will show up here.</p> : orders.filter((order) => order.feedback).map((order) => <div className="feedback-card" key={order.id}><span className="feedback-avatar">{order.student[0]}</span><div><b>{order.student}</b><small>Order {order.id} · {new Date(order.createdAt).toLocaleDateString()}</small></div><span className="feedback-stars">{'★'.repeat(order.feedback ?? 0)}{'☆'.repeat(5 - (order.feedback ?? 0))}</span><p>Thanks for helping us make campus lunch a little better.</p></div>)}</div>}
  </section>
}

function Metric({ label, value, note, icon, color }: { label: string; value: string; note: string; icon: React.ReactNode; color: string }) { return <div className="metric-card"><span className={`stat-icon ${color}`}>{icon}</span><span className="metric-label">{label}</span><b className="metric-value">{value}</b><small>{note}</small></div> }
function AdminOrderRow({ order, items, compact, onStatus }: { order: Order; items: FoodItem[]; compact?: boolean; onStatus: (id: string, status: OrderStatus) => void }) {
  const next: Partial<Record<OrderStatus, OrderStatus>> = { Received: 'Accepted', Accepted: 'Preparing', Preparing: 'Ready', Ready: 'Completed' }
  const labels: Partial<Record<OrderStatus, string>> = { Received: 'Accept order', Accepted: 'Start prep', Preparing: 'Mark ready', Ready: 'Complete' }
  return <div className={compact ? 'admin-order-row compact' : 'admin-order-row'}><div className="admin-order-id"><span className="line-category">{order.id}</span><b>{order.student}</b><small>{order.studentId}</small></div><div className="admin-order-items"><b>{order.lines.map((line) => `${line.quantity}× ${items.find((item) => item.id === line.itemId)?.name ?? 'Menu item'}`).join(', ')}</b><small><Clock3 size={12} /> Pickup {order.slot}</small></div><span className={`status-pill status-${order.status.toLowerCase()}`}><i />{order.status}</span><b className="admin-order-total">{money(order.total)}</b>{order.status === 'Received' ? <span className="admin-initial-actions"><button className="button button-dark admin-action" onClick={() => onStatus(order.id, 'Accepted')}>Accept <ArrowRight size={14} /></button><button className="reject-button" onClick={() => onStatus(order.id, 'Rejected')}>Reject</button></span> : next[order.status] ? <button className="button button-dark admin-action" onClick={() => onStatus(order.id, next[order.status]!)}>{labels[order.status]} <ArrowRight size={14} /></button> : <span className="admin-order-done">{order.status === 'Cancelled' ? 'Cancelled by student' : order.status === 'Rejected' ? 'Rejected' : 'Done'}</span>}</div>
}

function ItemModal({ item, onClose, onAdd }: { item: FoodItem; onClose: () => void; onAdd: (item: FoodItem, quantity: number, extras: string[]) => void }) {
  const [quantity, setQuantity] = useState(1); const [extras, setExtras] = useState<string[]>([])
  const extraPrice = (extra: string) => extra.toLowerCase().includes('cheese') ? 10 : 5
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="item-modal modal-card"><button className="modal-close" onClick={onClose} aria-label="Close details"><X size={19} /></button><div className="modal-food-image"><img src={item.image} alt={item.name} onError={(event) => { event.currentTarget.src = imageFallback }} /><span className={item.vegetarian ? 'diet-badge veg-badge' : 'diet-badge nonveg-badge'}><i />{item.vegetarian ? 'VEG' : 'NON-VEG'}</span></div><div className="modal-food-body"><div className="line-category">{item.category.toUpperCase()} <span>·</span> <Star size={12} fill="currentColor" /> {item.rating}</div><h2>{item.name}</h2><p>{item.description}</p><div className="ingredient-list"><b>GOOD THINGS INSIDE</b><span>{item.ingredients.join(' · ')}</span></div>{item.extras.length > 0 && <div className="extra-options"><b>MAKE IT YOURS <small>OPTIONAL</small></b>{item.extras.map((extra) => <label key={extra}><span>{extra}<small> +{money(extraPrice(extra))}</small></span><input type="checkbox" checked={extras.includes(extra)} onChange={() => setExtras((current) => current.includes(extra) ? current.filter((value) => value !== extra) : [...current, extra])} /></label>)}</div>}<div className="modal-bottom"><div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity"><Minus size={14} /></button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity"><Plus size={14} /></button></div><button className="button button-dark modal-add" disabled={!item.available} onClick={() => onAdd(item, quantity, extras)}>{item.available ? <>Add to bag <b>{money((item.price + extras.reduce((sum, extra) => sum + extraPrice(extra), 0)) * quantity)}</b></> : 'Currently unavailable'}</button></div></div></section></div>
}

function CheckoutModal({ slots, total, onClose, onConfirm, onSignIn, user }: { slots: typeof pickupSlots; total: number; onClose: () => void; onConfirm: (slot: string, payment: string) => void; onSignIn: () => void; user: User | null }) {
  const [slot, setSlot] = useState(''); const [payment, setPayment] = useState('Pay at counter')
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="checkout-modal modal-card"><div className="checkout-modal-head"><div><div className="eyebrow muted-eyebrow">ALMOST LUNCH</div><h2>Pick your moment<span>.</span></h2></div><button className="modal-close" onClick={onClose} aria-label="Close checkout"><X size={18} /></button></div>{!user && <div className="guest-note"><span><LogIn size={16} /></span><div><b>Ordering as a guest</b><small>Sign in to keep a history of your orders.</small></div><button onClick={onSignIn}>Sign in</button></div>}<div className="checkout-label"><b>01</b><span><strong>Choose a pickup slot</strong><small>Today · slots have limited capacity</small></span></div><div className="slot-grid">{slots.map((pickup) => <button key={pickup.time} disabled={pickup.remaining === 0} className={`slot-button ${slot === pickup.time ? 'slot-selected' : ''} ${pickup.remaining === 0 ? 'slot-full' : ''}`} onClick={() => setSlot(pickup.time)}><span>{pickup.time}</span><small>{pickup.remaining === 0 ? 'FULL' : `${pickup.remaining} / ${pickup.capacity} left`}</small></button>)}</div><div className="checkout-label payment-label"><b>02</b><span><strong>Payment at pickup</strong><small>Simple, secure, no checkout surprises</small></span></div><div className="payment-options">{['Pay at counter', 'UPI at counter'].map((option) => <button key={option} className={payment === option ? 'payment-option payment-selected' : 'payment-option'} onClick={() => setPayment(option)}><span className="payment-icon"><CreditCard size={16} /></span><span>{option}<small>{option === 'Pay at counter' ? 'Cash or card' : 'Scan & pay when you collect'}</small></span><i>{payment === option && <Check size={12} />}</i></button>)}</div><div className="checkout-total"><span>Pay at pickup</span><b>{money(total)}</b></div><button className="button button-dark confirm-button" disabled={!slot} onClick={() => onConfirm(slot, payment)}>Confirm my order <ArrowRight size={17} /></button><p className="checkout-footnote"><BadgeCheck size={13} /> You can cancel until the kitchen accepts your order.</p></section></div>
}

function AuthModal({ onClose, onSignIn }: { onClose: () => void; onSignIn: (role: 'student' | 'admin', name: string, collegeId: string) => void }) {
  const [mode, setMode] = useState<'student' | 'admin' | 'register'>('student'); const [name, setName] = useState(''); const [collegeId, setCollegeId] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="auth-modal modal-card"><button className="modal-close" onClick={onClose} aria-label="Close sign in"><X size={18} /></button><span className="auth-mark"><UtensilsCrossed size={20} /></span><div className="eyebrow muted-eyebrow">WELCOME TO THE TABLE</div><h2>{mode === 'register' ? 'Join the lunch club.' : 'Good to see you.'}</h2><p>{mode === 'register' ? 'A few details and your next lunch is sorted.' : 'Sign in for a smoother campus lunch.'}</p><div className="auth-tabs"><button className={mode !== 'admin' ? 'auth-tab selected' : 'auth-tab'} onClick={() => setMode('student')}>Student</button><button className={mode === 'admin' ? 'auth-tab selected' : 'auth-tab'} onClick={() => setMode('admin')}>Canteen staff</button></div><form onSubmit={(event) => { event.preventDefault(); onSignIn(mode === 'admin' ? 'admin' : 'student', name, collegeId) }}>{(mode === 'register' || mode === 'admin') && <label className="form-label">{mode === 'admin' ? 'Staff name' : 'Student name'}<input required value={name} onChange={(event) => setName(event.target.value)} placeholder={mode === 'admin' ? 'Canteen manager' : 'Your full name'} /></label>}<label className="form-label">{mode === 'admin' ? 'Staff ID' : 'College ID or email'}<input required value={collegeId} onChange={(event) => setCollegeId(event.target.value)} placeholder={mode === 'admin' ? 'STAFF-01' : 'e.g. 22CS014'} /></label>{mode === 'register' && <><label className="form-label">Branch, year & section<input required placeholder="Computer Science · Year 2 · A" /></label><label className="form-label">College email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@college.edu" /></label><label className="form-label">Phone number<input type="tel" required placeholder="10-digit mobile number" /></label></>}<label className="form-label">Password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 8 characters" minLength={8} /></label><button className="button button-dark auth-submit" type="submit">{mode === 'register' ? 'Create student account' : 'Sign in'} <ArrowRight size={16} /></button></form><p className="auth-switch">{mode === 'admin' ? 'Student instead?' : mode === 'register' ? 'Already on CampusBite?' : 'New around here?'} <button onClick={() => setMode(mode === 'admin' || mode === 'register' ? 'student' : 'register')}>{mode === 'admin' ? 'Student login' : mode === 'register' ? 'Sign in' : 'Create an account'}</button></p><p className="demo-hint">Demo mode: any ID and password work locally. Passwords are never stored.</p></section></div>
}

function OffersPage({ onMenu }: { onMenu: () => void }) { return <section className="inner-page offers-page"><div className="eyebrow muted-eyebrow">A LITTLE SOMETHING EXTRA</div><h1>Good food.<br /><em>Better deals.</em></h1><p className="offers-intro">Small treats for the people who make this campus feel like home.</p><div className="offer-grid"><article className="offer-card offer-orange"><span className="offer-number">01 / LUNCH CLUB</span><span className="offer-illustration">₹20</span><div><span className="offer-tag">YOUR FIRST ₹200+</span><h2>A little off<br />your first feast.</h2><p>Get ₹20 off orders over ₹200. Automatically yours.</p><button onClick={onMenu}>Find your lunch <ArrowRight size={15} /></button></div></article><article className="offer-card offer-green"><span className="offer-number">02 / DAILY RITUAL</span><span className="offer-illustration">☕</span><div><span className="offer-tag">THE 2 PM RESET</span><h2>Take five.<br />Tea's on us.</h2><p>Ask at the counter for today's afternoon tea special.</p><button onClick={onMenu}>See the menu <ArrowRight size={15} /></button></div></article></div></section> }

function AboutPage({ onMenu }: { onMenu: () => void }) {
  return <section className="inner-page about-page"><div className="eyebrow muted-eyebrow">A LITTLE MORE ABOUT US</div><h1>Campus lunch,<br /><em>without the rush.</em></h1><p className="offers-intro">CampusBite brings the canteen a little closer to your timetable. Order ahead, choose a pickup window, and collect something fresh between classes.</p><div className="about-image"><img src="https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=85" alt="Freshly prepared dishes ready to share" /></div><div className="about-details"><div><span className="line-category">MADE FOR CAMPUS LIFE</span><h2>Good food should fit your day.</h2></div><p>From a quick chai between lectures to a proper lunch with friends, our canteen team prepares familiar favourites fresh each day. Pickup windows help spread the lunch rush, so your break stays yours.</p></div><div className="about-hours"><span><b>Kitchen hours</b><small>Monday to Saturday</small></span><strong>8:00 AM – 5:00 PM</strong><button className="button button-dark" onClick={onMenu}>See what's cooking <ArrowRight size={16} /></button></div></section>
}