export type FoodItem = { id: string; name: string; description: string; category: 'Snacks' | 'Meals' | 'Beverages' | 'Desserts'; price: number; rating: number; vegetarian: boolean; available: boolean; popular: boolean; popularScore: number; image: string; ingredients: string[]; extras: string[] }
export type OrderStatus = 'Received' | 'Accepted' | 'Preparing' | 'Ready' | 'Completed' | 'Cancelled' | 'Rejected'
export type Order = { id: string; student: string; studentId: string; lines: { itemId: string; quantity: number; extras: string[] }[]; total: number; slot: string; payment: string; status: OrderStatus; createdAt: string; feedback: number | null }
export type User = { name: string; collegeId: string; role: 'student' | 'admin' }
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=850&q=85`
export const biryaniImage = photo('photo-1589302168068-964664d93dc0')
export const limeCoolerImage = 'https://images.pexels.com/photos/9996448/pexels-photo-9996448.jpeg?auto=compress&cs=tinysrgb&w=850'
export const buttermilkImage = 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=850&q=85'
export const gulabJamunImage = 'https://images.pexels.com/photos/7406887/pexels-photo-7406887.jpeg?auto=compress&cs=tinysrgb&w=850'
export const initialItems: FoodItem[] = [
  { id: 'sandwich', name: 'Garden club sandwich', description: 'Toasted sourdough, crisp greens, house green chutney.', category: 'Snacks', price: 50, rating: 4.8, vegetarian: true, available: true, popular: true, popularScore: 148, image: photo('photo-1528735602780-2552fd46c7af'), ingredients: ['Sourdough', 'Cucumber', 'Tomato', 'Mint chutney'], extras: ['Extra cheese', 'Extra sauce'] },
  { id: 'burger', name: 'Campus smash burger', description: 'Crispy potato patty, sharp cheddar, tangy campus sauce.', category: 'Snacks', price: 90, rating: 4.9, vegetarian: true, available: true, popular: true, popularScore: 126, image: photo('photo-1568901346375-23c9450c58cd'), ingredients: ['Potato patty', 'Cheddar', 'Lettuce', 'House sauce'], extras: ['Extra cheese', 'Extra sauce'] },
  { id: 'samosa', name: 'Golden samosa', description: 'Flaky pastry filled with spiced potato and peas. Two to a plate.', category: 'Snacks', price: 25, rating: 4.7, vegetarian: true, available: true, popular: true, popularScore: 189, image: photo('photo-1601050690597-df0568f70950'), ingredients: ['Potato', 'Green peas', 'Cumin', 'Flaky pastry'], extras: ['Extra sauce'] },
  { id: 'fries', name: 'Masala fries', description: 'Golden, crisp-cut fries tossed in our house masala.', category: 'Snacks', price: 60, rating: 4.5, vegetarian: true, available: true, popular: false, popularScore: 82, image: photo('photo-1573080496219-bb080dd4f877'), ingredients: ['Potato', 'House masala', 'Sea salt'], extras: ['Extra cheese', 'Extra sauce'] },
  { id: 'paneer-roll', name: 'Paneer tikka roll', description: 'Smoky paneer, crunchy onions and mint chutney in a warm wrap.', category: 'Snacks', price: 75, rating: 4.7, vegetarian: true, available: true, popular: false, popularScore: 64, image: photo('photo-1626700051175-6818013e1d4f'), ingredients: ['Paneer tikka', 'Onion', 'Mint chutney', 'Flatbread'], extras: ['Extra cheese', 'Extra sauce'] },
  { id: 'chicken-popcorn', name: 'Crispy chicken bites', description: 'Bite-size chicken, seasoned and fried crisp. Served with dip.', category: 'Snacks', price: 95, rating: 4.6, vegetarian: false, available: true, popular: false, popularScore: 58, image: photo('photo-1626082927389-6cd097cdc6ec'), ingredients: ['Chicken', 'House seasoning', 'Crumb coating'], extras: ['Extra sauce'] },
  { id: 'fried-rice', name: 'Wok-tossed fried rice', description: 'Smoky wok-fried rice with garden vegetables and spring onion.', category: 'Meals', price: 110, rating: 4.6, vegetarian: true, available: true, popular: true, popularScore: 106, image: photo('photo-1603133872878-684f208fb84b'), ingredients: ['Basmati rice', 'Seasonal vegetables', 'Spring onion', 'Soy'], extras: ['Extra sauce'] },
  { id: 'noodles', name: 'Chilli garlic noodles', description: 'Noodles with a little heat, plenty of garlic, zero regrets.', category: 'Meals', price: 100, rating: 4.7, vegetarian: true, available: true, popular: true, popularScore: 99, image: photo('photo-1569718212165-3a8278d5f624'), ingredients: ['Noodles', 'Garlic', 'Chilli', 'Seasonal vegetables'], extras: ['Extra cheese', 'Extra sauce'] },
  { id: 'biryani', name: 'Dum veg biryani', description: 'Slow-cooked fragrant rice, whole spices, cool raita on the side.', category: 'Meals', price: 140, rating: 4.9, vegetarian: true, available: true, popular: true, popularScore: 172, image: biryaniImage, ingredients: ['Basmati rice', 'Whole spices', 'Seasonal vegetables', 'Raita'], extras: ['Extra sauce'] },
  { id: 'thali', name: 'Everyday mini thali', description: 'Dal, seasonal sabzi, rice, two rotis. A proper lunch, sorted.', category: 'Meals', price: 120, rating: 4.6, vegetarian: true, available: true, popular: false, popularScore: 73, image: photo('photo-1547592180-85f173990554'), ingredients: ['Dal', 'Seasonal sabzi', 'Rice', 'Roti', 'Pickle'], extras: [] },
  { id: 'paneer-rice', name: 'Paneer curry & jeera rice', description: 'Creamy paneer curry with cumin-scented rice and a little salad.', category: 'Meals', price: 150, rating: 4.8, vegetarian: true, available: true, popular: false, popularScore: 71, image: photo('photo-1631452180519-c014fe946bc7'), ingredients: ['Paneer', 'Tomato gravy', 'Jeera rice', 'Fresh cream'], extras: ['Extra sauce'] },
  { id: 'egg-curry-rice', name: 'Egg curry rice bowl', description: 'Two boiled eggs in warm masala curry over steamed rice.', category: 'Meals', price: 125, rating: 4.6, vegetarian: false, available: true, popular: false, popularScore: 53, image: photo('photo-1603894584373-5ac82b2ae398'), ingredients: ['Egg', 'Masala gravy', 'Steamed rice', 'Coriander'], extras: ['Extra sauce'] },
  { id: 'tea', name: 'Cutting chai', description: 'Strong, milky, just sweet enough. A campus classic.', category: 'Beverages', price: 15, rating: 4.9, vegetarian: true, available: true, popular: true, popularScore: 210, image: photo('photo-1571934811356-5cc061b6821f'), ingredients: ['Assam tea', 'Milk', 'Ginger', 'Cardamom'], extras: [] },
  { id: 'coffee', name: 'Cold brew coffee', description: '18-hour steeped coffee, poured over ice. Your 2 pm sorted.', category: 'Beverages', price: 65, rating: 4.8, vegetarian: true, available: true, popular: true, popularScore: 115, image: photo('photo-1517701550927-30cf4ba1dba5'), ingredients: ['Single-origin coffee', 'Filtered water', 'Ice'], extras: [] },
  { id: 'juice', name: 'Seasonal fresh juice', description: 'Today’s fruit, squeezed fresh. Ask us what’s in season.', category: 'Beverages', price: 45, rating: 4.4, vegetarian: true, available: false, popular: false, popularScore: 56, image: photo('photo-1600271886742-f049cd451bba'), ingredients: ['Seasonal fruit'], extras: [] },
  { id: 'lemonade', name: 'Fresh lime cooler', description: 'Fresh lime, a pinch of salt and plenty of ice. Bright and breezy.', category: 'Beverages', price: 35, rating: 4.6, vegetarian: true, available: true, popular: false, popularScore: 48, image: limeCoolerImage, ingredients: ['Fresh lime', 'Mint', 'Black salt', 'Ice'], extras: [] },
  { id: 'buttermilk', name: 'Masala buttermilk', description: 'Cool salted buttermilk with roasted cumin and fresh coriander.', category: 'Beverages', price: 25, rating: 4.5, vegetarian: true, available: true, popular: false, popularScore: 43, image: buttermilkImage, ingredients: ['Curd', 'Roasted cumin', 'Coriander', 'Black salt'], extras: [] },
  { id: 'cake', name: 'Chocolate fudge slice', description: 'Deep cocoa, soft middle, baked fresh by the canteen team.', category: 'Desserts', price: 55, rating: 4.8, vegetarian: true, available: true, popular: true, popularScore: 87, image: photo('photo-1578985545062-69928b1d9587'), ingredients: ['Cocoa', 'Dark chocolate', 'Flour', 'Butter'], extras: [] },
  { id: 'ice-cream', name: 'Mango ice cream', description: 'A scoop of sunshine made with real Alphonso mango.', category: 'Desserts', price: 40, rating: 4.7, vegetarian: true, available: true, popular: false, popularScore: 62, image: photo('photo-1563805042-7684c019e1cb'), ingredients: ['Alphonso mango', 'Fresh cream', 'Milk'], extras: [] },
  { id: 'gulab-jamun', name: 'Warm gulab jamun', description: 'Two soft milk dumplings in cardamom syrup, served warm.', category: 'Desserts', price: 35, rating: 4.8, vegetarian: true, available: true, popular: false, popularScore: 69, image: gulabJamunImage, ingredients: ['Milk solids', 'Cardamom', 'Sugar syrup'], extras: [] },
  { id: 'brownie', name: 'Walnut brownie', description: 'A fudgy chocolate square with toasted walnuts on top.', category: 'Desserts', price: 65, rating: 4.7, vegetarian: true, available: true, popular: false, popularScore: 57, image: photo('photo-1606313564200-e75d5e30476c'), ingredients: ['Dark chocolate', 'Cocoa', 'Walnuts', 'Butter'], extras: [] },
]
export const pickupSlots = [
  { time: '11:30 – 11:45 AM', capacity: 10, remaining: 4 }, { time: '11:45 AM – 12:00 PM', capacity: 10, remaining: 8 },
  { time: '12:00 – 12:15 PM', capacity: 10, remaining: 2 }, { time: '12:15 – 12:30 PM', capacity: 10, remaining: 6 },
  { time: '12:30 – 12:45 PM', capacity: 10, remaining: 0 }, { time: '12:45 – 1:00 PM', capacity: 10, remaining: 5 },
]
export const initialOrders: Order[] = []